apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
spec:
  analysis:
    interval: 1m
    maxWeight: 50
    metrics:
    - interval: 1m
      name: request-success-rate
      thresholdRange:
        min: 99
    - interval: 30s
      name: request-duration
      thresholdRange:
        max: 500
    stepWeight: 10
    threshold: 5
    webhooks:
    - metadata:
        cmd: curl -sd 'test' http://podinfo-canary:9898/token | grep token
        type: bash
      name: acceptance-test
      timeout: 30s
      type: pre-rollout
      url: http://flagger-loadtester.test/
    - metadata:
        cmd: hey -z 1m -q 10 -c 2 http://podinfo-canary.test:9898/
      name: load-test
      timeout: 5s
      url: http://flagger-loadtester.test/
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: podinfo
  progressDeadlineSeconds: 60
  service:
    gateways:
    - istio-system/public-gateway
    hosts:
    - test.example.com
    port: 9898
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: gateway-error,connect-failure,refused-stream
    targetPort: 9898
    trafficPolicy:
      tls:
        mode: DISABLE
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
